# Generated by Django 4.1.13 on 2025-02-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remarkableplace',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='weathersummary',
            options={'verbose_name': 'Прогноз погоды', 'verbose_name_plural': 'Прогнозы погоды'},
        ),
    ]
