# Generated by Django 5.1.6 on 2025-02-22 15:18

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_remarkableplace_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remarkableplace',
            options={'verbose_name': 'Примечательное места', 'verbose_name_plural': 'Примечательные места'},
        ),
        migrations.AlterModelOptions(
            name='weathersummary',
            options={'verbose_name': 'Сводка погоды', 'verbose_name_plural': 'Сводки погоды'},
        ),
        migrations.AlterField(
            model_name='remarkableplace',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Гео-координаты места (точка)'),
        ),
        migrations.AlterField(
            model_name='remarkableplace',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название места'),
        ),
        migrations.AlterField(
            model_name='remarkableplace',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Рейтинг (от 0 до 25)'),
        ),
    ]
