# Generated by Django 4.1.13 on 2025-02-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_remarkableplace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersummary',
            name='humidity',
            field=models.IntegerField(editable=False, verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='weathersummary',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.remarkableplace', verbose_name='Примечательное место'),
        ),
        migrations.AlterField(
            model_name='weathersummary',
            name='pressure',
            field=models.FloatField(editable=False, verbose_name='Давление'),
        ),
        migrations.AlterField(
            model_name='weathersummary',
            name='temperature',
            field=models.FloatField(editable=False, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='weathersummary',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения задачи'),
        ),
        migrations.AlterField(
            model_name='weathersummary',
            name='wind_direction',
            field=models.CharField(editable=False, max_length=2, verbose_name='Направление ветра'),
        ),
        migrations.AlterField(
            model_name='weathersummary',
            name='wind_speed',
            field=models.FloatField(editable=False, verbose_name='Скорость ветра'),
        ),
    ]
