# Generated by Django 4.1.13 on 2025-02-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_weathersummary_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersummary',
            name='place',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='places.remarkableplace', verbose_name='Примечательное место'),
        ),
    ]
